# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_remove_photo_filtered_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/original'),
        ),
    ]
